name: Deploy portfolio website
on: push
jobs:
    setup-prerequisites:
        name: deploy-proj
        runs-on: ubuntu-latest
        steps:
        - name: Install AWSCLI
          uses: unfor19/install-aws-cli-action@v1

        - name: Setup AWS CLI
          run: aws sts get-caller-identity
            